/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionInquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
  'course' : string,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Testimonial {
  'review' : string,
  'studentName' : string,
  'createdAt' : Time,
  'rating' : bigint,
  'course' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAdmissionInquiryAdmin' : ActorMethod<[bigint], boolean>,
  'getAdmissionInquiriesAdmin' : ActorMethod<[], Array<AdmissionInquiry>>,
  'getAdmissionInquiriesWithIdsAdmin' : ActorMethod<
    [],
    Array<[bigint, AdmissionInquiry]>
  >,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissionsAdmin' : ActorMethod<[], Array<ContactSubmission>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAdmissionInquiry' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'submitContact' : ActorMethod<[string, string, string], undefined>,
  'submitTestimonial' : ActorMethod<
    [string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];